/* eslint-disable @next/next/no-img-element */
import styles from "./clients.module.css";

const Logos = [
  "/clients/Item.png",
  "/clients/Item-1.png",
  "/clients/Item-2.png",
  "/clients/Item-3.png",
  "/clients/Item-4.png",
  "/clients/Item-5.png",
  "/clients/Item-6.png",
  "/clients/Item-7.png",
  "/clients/Item-8.png",
  "/clients/Item-9.png",
  "/clients/Item-10.png",
  "/clients/Item-11.png",
  "/clients/Item-12.png",
  "/clients/Item-13.png",
  "/clients/Item-14.png",
  "/clients/Item-15.png",
  "/clients/Item-16.png",
  "/clients/Item-17.png",
  "/clients/Item-18.png",
  "/clients/Item-19.png",
  "/clients/Item-20.png",
  "/clients/Item-21.png",
  "/clients/Item-22.png",
  "/clients/Item-23.png",
  "/clients/Item-24.png",
  "/clients/Item-25.png",
  "/clients/Item-26.png",
  "/clients/Item-27.png",
  "/clients/Item-28.png",
  "/clients/Item-29.png",
  "/clients/Item-30.png",
  "/clients/Item-31.png",
  "/clients/Item-32.png",
  "/clients/Item-33.png",
  "/clients/Item-34.png",
  "/clients/Item-35.png",
  "/clients/Item-36.png",
  "/clients/Item-37.png",
  "/clients/Item-38.png",
  "/clients/Item-39.png",
  "/clients/Item-40.png",
  "/clients/Item-41.png",
  "/clients/Item-42.png",
  "/clients/Item-43.png",
  "/clients/Item-44.png",
  "/clients/Item-45.png",
  "/clients/Item-46.png",
  "/clients/Item-47.png",
  "/clients/Item-48.png",
  "/clients/Item-49.png",
  "/clients/Item-50.png",
  "/clients/Item-51.png",
  "/clients/Item-52.png",
  "/clients/Item-53.png",
  "/clients/Item-54.png",
  "/clients/Item-55.png",
  "/clients/Item-56.png",
  "/clients/Item-57.png",
  "/clients/Item-58.png",
  "/clients/Item-59.png",
  "/clients/Item-60.png",
  "/clients/Item-61.png",
  "/clients/Item-62.png",
  "/clients/Item-63.png",
  "/clients/Item-64.png",
  "/clients/Item-65.png",
  "/clients/Item-66.png",
  "/clients/Item-67.png",
  "/clients/Item-68.png",
  "/clients/Item-69.png",
  "/clients/Item-70.png",
  "/clients/Item-71.png",
  "/clients/Item-72.png",
  "/clients/Item-73.png",
  "/clients/Item-74.png",
  "/clients/Item-75.png",
  "/clients/Item-76.png",
  "/clients/Item-77.png",
  "/clients/Item-78.png",
  "/clients/Item-79.png",
  "/clients/Item-80.png",
  "/clients/Item-81.png",
  "/clients/Item-82.png",
  "/clients/Item-83.png",
  "/clients/Item-84.png",
  "/clients/Item-85.png",
  "/clients/Item-86.png",
  "/clients/Item-87.png",
  "/clients/Item-88.png",
  "/clients/Item-89.png",
  "/clients/Item-90.png",
  "/clients/Item-91.png",
  "/clients/Item-92.png",
  "/clients/Item-93.png",
  "/clients/Item-94.png",
  "/clients/Item-95.png",
  "/clients/Item-96.png",
  "/clients/Item-97.png",
  "/clients/Item-98.png",
  "/clients/Item-99.png",
  "/clients/Item-100.png",
  "/clients/Item-101.png",
  "/clients/Item-102.png",
  "/clients/Item-103.png",
  "/clients/Item-104.png",
  "/clients/Item-105.png",
  "/clients/Item-106.png",
  "/clients/Item-107.png",
  "/clients/Item-108.png",
  "/clients/Item-109.png",
  "/clients/Item-110.png",
  "/clients/Item-111.png",
  "/clients/Item-112.png",
  "/clients/Item-113.png",
  "/clients/Item-114.png",
  "/clients/Item-115.png",
  "/clients/Item-116.png",
  "/clients/Item-117.png",
];

function Clients() {
  return (
    <section className={styles.clients}>
      <div className="container">
        <div className={styles.rowMainClients}>
          <h2 className="h2">Our Clients</h2>
          <div className={styles.rowClients}>
            {Logos.map((logo) => (
              <div key={logo} className={styles.columnClients}>
                <img src={logo} alt="image" />
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

export default Clients;
